import Head from 'next/head';
import Link from 'next/link';
import { Button } from 'react-daisyui';

export default function Home() {
  return (
    <>
      <Head>
        <title>ReactHookForm With Zod Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid h-screen place-content-center place-items-center gap-4">
        <h1 className="text-2xl font-bold underline">
          React Hook Form With Zod Demo
        </h1>
        <Link href="/sign-up">
          <Button color="primary">Sign Up</Button>
        </Link>
      </main>
    </>
  );
}
