import Head from 'next/head';
import Link from 'next/link';
import { Button } from 'react-daisyui';

export default function Home() {
  return (
    <>
      <Head>
        <title>ReactHookForm With Zod Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid h-screen place-content-center place-items-center gap-8">
        <h1 className="text-2xl font-bold">
          React-hook-form과 Zod을 사용해보기
        </h1>
        <Link href="/sign-up">
          <Button color="primary">가입하기</Button>
        </Link>
      </main>
    </>
  );
}
